name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Check Node.js and npm version
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm install

      - name: Debug Build Process
        run: |
          echo "Checking build configuration..."
          cat package.json
          echo "Checking environment variables..."
          env | grep GH_TOKEN || echo "GH_TOKEN is not set"
          echo "Running build process..."
          npm run build --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: electron-app
          path: dist/